Digidennis:
  SitePack:
    Slick:
      'useCss': TRUE
      'renderBackend': TRUE
    GoogleMaps:
          googleApiKey: 'AIzaSyAYdNhIWrA3eKa_WPh1_IXt3JPBDR4SiqE'

Neos:
  Neos:
    fusion:
      autoInclude:
        'Digidennis.SitePack': TRUE
    userInterface:
      translation:
        autoInclude:
          'Digidennis.SitePack': ['NodeTypes/*']